var AP2CourseDaysJSON = [
{"courseDayTitle":"AP2-01","courseDayDate":"01/06/20"},
{"courseDayTitle":"AP2-02","courseDayDate":"01/09/20"},
{"courseDayTitle":"AP2-03","courseDayDate":"01/13/20"},
{"courseDayTitle":"AP2-04","courseDayDate":"01/16/20"},
{"courseDayTitle":"AP2-05","courseDayDate":"01/23/20"},
{"courseDayTitle":"AP2-06","courseDayDate":"01/27/20"},
{"courseDayTitle":"AP2-07","courseDayDate":"01/30/20"},
{"courseDayTitle":"AP2-08","courseDayDate":"02/03/20"},
{"courseDayTitle":"AP2-09","courseDayDate":"02/06/20"},
{"courseDayTitle":"AP2-10","courseDayDate":"02/10/20"},
{"courseDayTitle":"AP2-11","courseDayDate":"02/13/20"},
{"courseDayTitle":"AP2-12","courseDayDate":"02/20/20"},
{"courseDayTitle":"AP2-13","courseDayDate":"02/24/20"},
{"courseDayTitle":"AP2-14","courseDayDate":"02/27/20"},
{"courseDayTitle":"AP2-15","courseDayDate":"03/02/20"}
];

var AP2ReadingsJSON = [
{"readingDate":"01/06/20","readingAuthors":["Brian Laslie"],"readingTitle":"The Air Force Way of War","readingPages":["ix-98"]},
{"readingDate":"01/06/20","readingAuthors":["Colin Gray"],"readingTitle":"Airpower Reborn","readingPages":["156-180"]},
{"readingDate":"01/09/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-30: Command and Control of Joint Air Operations","readingPages":["Ch 1 & Ch 2"]},
{"readingDate":"01/09/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine Annex 3-30: Command and Control","readingPages":["Commanding Airpower"]},
{"readingDate":"01/13/20","readingAuthors":["John Andreas Olsen"],"readingTitle":"A History of Air Warfare","readingPages":["177-200"]},
{"readingDate":"01/13/20","readingAuthors":["Michael R. Gordon & Bernard E. Trainor"],"readingTitle":"The General's War","readingPages":["Chaps. 4, 5, 9, 15"]},
{"readingDate":"01/13/20","readingAuthors":["Thomas A. Keaney & Eliot A. Cohen"],"readingTitle":"Gulf War Airpower Survey Summary Report","readingPages":["235-251"]},
{"readingDate":"01/16/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-30: Command and Control of Joint Air Operations","readingPages":["Ch 3"]},
{"readingDate":"01/16/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine Annex 3-30: Command and Control","readingPages":["Command & Control Mechanisms","Air Operations Center", "Liasons in the AOC", "The Joint Air Component Coordination Element", "App B: The Air Operations Center", "App D: The Theater Air Control System"]},
{"readingDate":"01/16/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine Annex 3-30: Operations and Planning","readingPages":["The Joint Operation Planning Process for Air"]},
{"readingDate":"01/23/20","readingAuthors":["John Andreas Olsen"],"readingTitle":"A History of Air Warfare","readingPages":["225-252"]},
{"readingDate":"01/23/20","readingAuthors":["John Keegan"],"readingTitle":"Please Mr. Blair, Never Take Such a Risk Again","readingPages":["all"]},
{"readingDate":"01/23/20","readingAuthors":["DoD"],"readingTitle":"JP 3-03 Joint Interdiction","readingPages":["Executive Summary"]},
{"readingDate":"01/23/20","readingAuthors":["USAF"],"readingTitle":"319","readingPages":["Air Interdiction"]},
{"readingDate":"01/23/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine Annex 3-70: Strategic Attack","readingPages":["Introduction & Fundamentals of Strategic Attack"]},
{"readingDate":"01/27/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-35: Deployment and Redeployment Operations","readingPages":["Executive Summary"]},
{"readingDate":"01/27/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine Annex 3-30: Command and Control","readingPages":["Organizing Air Force Forces"]},
{"readingDate":"01/27/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-17: Air Mobility Operations","readingPages":["Executive Summary"]},
{"readingDate":"01/27/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine Annex 3-17: Air Mobility Operations","readingPages":["Introduction of Air Mobility Operations"]},
{"readingDate":"01/30/20","readingAuthors":["John Andreas Olsen"],"readingTitle":"A History of Air Warfare","readingPages":["255-296"]},
{"readingDate":"01/30/20","readingAuthors":["Richard B. Andreas & Jeffrey B. Hukill"],"readingTitle":"Anaconda A Flawed Joint Planning Process","readingPages":["135-140"]},
{"readingDate":"01/30/20","readingAuthors":["Clinton B. Romesha"],"readingTitle":"Red Platoon","readingPages":["105-117", "261-293"]},
{"readingDate":"01/30/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-09.3: Close Air Support","readingPages":["Executive Summary"]},
{"readingDate":"01/30/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine Annex 3-03: Counterland Operations","readingPages":["Close Air Support"]},
{"readingDate":"02/03/20","readingAuthors":["N/A"],"readingTitle":"Midterm Papers Due","readingPages":["none"]},
{"readingDate":"02/06/20","readingAuthors":["Everett C. Dolman"],"readingTitle":"Geostrategy in the Space Age: An Astropolitical Analysis","readingPages":["all"]},
{"readingDate":"02/06/20","readingAuthors":["William J. Liquori Jr. & B. Chance Saltzman"],"readingTitle":"Counterspace Command And Control","readingPages":["all"]},
{"readingDate":"02/06/20","readingAuthors":["Everett C. Dolman"],"readingTitle":"Space Force déjà vu","readingPages":["all"]},
{"readingDate":"02/06/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-14: Joint Space Operations","readingPages":["Ch 2: Space Operations and the Joint Funcitons"]},
{"readingDate":"02/06/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine Annex 3-14: Counterspace Operations","readingPages":["all"]},
{"readingDate":"02/10/20","readingAuthors":["David Sanger"],"readingTitle":"The Perfect Weapon","readingPages":["vii-xix", "1-5", "100-151", "215-239", "318-331"]},
{"readingDate":"02/10/20","readingAuthors":["DoD"],"readingTitle":"Summary: Department of Defense Cyber Strategy","readingPages":["1-7"]},
{"readingDate":"02/10/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-12: Cyberspace Operations","readingPages":["Ch 2: Cyberspace Operations Core Activities"]},
{"readingDate":"02/10/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine 3-12: Cyberspace Operatins","readingPages":["Intro to Cyberspace Operations"]},
{"readingDate":"02/13/20","readingAuthors":["Dana Pittard & Wes Bryant"],"readingTitle":"Hunting the Caliphate","readingPages":["xiii-xvi", "69-84", "222-319"]},
{"readingDate":"02/13/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-0: Joint Operations","readingPages":["Ch 3: Joint Functions", "Ch 4: Intelligence"]},
{"readingDate":"02/13/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine Annex 2-0: Global Integrated Intelligence, Survelliance, and Reconnaissance Operations","readingPages":["Intro to Global Integrated ISR"]},
{"readingDate":"02/13/20","readingAuthors":["USAF"],"readingTitle":"USAF Doctrine Annex 3-01: Counterair Operations","readingPages":["Counterair Operations"]},
{"readingDate":"02/20/20","readingAuthors":["N/A"],"readingTitle":"Project Seminar","readingPages":["none"]},
{"readingDate":"02/24/20","readingAuthors":["N/A"],"readingTitle":"No Reading","readingPages":["none"]},
{"readingDate":"02/24/20","readingAuthors":["N/A"],"readingTitle":"Project Seminar","readingPages":["none"]},
{"readingDate":"03/02/20","readingAuthors":["N/A"],"readingTitle":"Project Seminar","readingPages":["none"]}
];
