var IS1CourseDaysJSON = [
{"courseDayTitle":"IS1-01","courseDayDate":"10/15/19"},
{"courseDayTitle":"IS1-02","courseDayDate":"10/18/19"},
{"courseDayTitle":"IS1-03","courseDayDate":"10/22/19"},
{"courseDayTitle":"IS1-04","courseDayDate":"10/25/19"},
{"courseDayTitle":"IS1-05","courseDayDate":"10/29/19"},
{"courseDayTitle":"IS1-06","courseDayDate":"11/05/19"},
{"courseDayTitle":"IS1-07","courseDayDate":"11/08/19"},
{"courseDayTitle":"IS1-08","courseDayDate":"11/12/19"},
{"courseDayTitle":"IS1-09","courseDayDate":"11/19/19"},
{"courseDayTitle":"IS1-10","courseDayDate":"11/22/19"},
{"courseDayTitle":"IS1-11","courseDayDate":"11/26/19"},
{"courseDayTitle":"IS1-12","courseDayDate":"12/03/19"},
{"courseDayTitle":"IS1-13","courseDayDate":"12/06/19"},
{"courseDayTitle":"IS1-14","courseDayDate":"12/13/19"},
{"courseDayTitle":"IS1-15","courseDayDate":"12/17/19"}];

var IS1ReadingsJSON = [
{"readingDate":"10/15/19","readingAuthors":["Jack S. Levy"],"readingTitle":"The Causes of War and the Conditions of Peace","readingPages":["139-165"]},
{"readingDate":"10/15/19","readingAuthors":["Selina Kaur Rai"],"readingTitle":"What Were the Causes and Consequences of the 1948 Arab-Israeli War?","readingPages":["All"]},
{"readingDate":"10/15/19","readingAuthors":["Alexander Liffiton"],"readingTitle":"The Falklands War: Differing Causes of Conflict","readingPages":["All"]},
{"readingDate":"10/18/19","readingAuthors":["John J. Mearsheimer"],"readingTitle":"The Tragedy of Great Power Politics","readingPages":["17-22","29-54"]},
{"readingDate":"10/18/19","readingAuthors":["Kenneth Waltz"],"readingTitle":"Theory of International Politics","readingPages":["123-128","161-193"]},
{"readingDate":"10/18/19","readingAuthors":["Keir A. Lieber"],"readingTitle":"The New History of World War I and What it Means for International Relations Theory","readingPages":["155-191"]},
{"readingDate":"10/22/19","readingAuthors":["Jack S. Levy"],"readingTitle":"Domestic Politics and War","readingPages":["653-673"]},
{"readingDate":"10/22/19","readingAuthors":["Patrick James","John R. Oneal"],"readingTitle":"The Influence of Domestic and International Politics on the President’s Use of Force","readingPages":["307-311"]},
{"readingDate":"10/22/19","readingAuthors":["Michael R. Gordon"],"readingTitle":"Domestic Conflict and the Origins of the First World War: The British and the German Cases","readingPages":["191-226"]},
{"readingDate":"10/25/19","readingAuthors":["Ole R. Holsti"],"readingTitle":"The Belief System and National Images: A Case Study","readingPages":["244-252"]},
{"readingDate":"10/25/19","readingAuthors":["Michelle Murray"],"readingTitle":"Identity, Insecurity, and Great Power Politics: The Tragedy of German Naval Ambition Before the First World War","readingPages":["656-688"]},
{"readingDate":"10/29/19","readingAuthors":["Stephen G. Brooks"],"readingTitle":"The Globalization of Production and the Changing Benefits of Conquest","readingPages":["646-670"]},
{"readingDate":"10/29/19","readingAuthors":["Mary Kaldor"],"readingTitle":"Nationalism and Globalization","readingPages":["161-177"]},
{"readingDate":"10/29/19","readingAuthors":["Lars-Erik Cederman"],"readingTitle":"Blood for Soil: The Fatal Temptations of Ethnic Politics","readingPages":["61-68"]},
{"readingDate":"10/29/19","readingAuthors":[" V. P. Gagnon"],"readingTitle":"Ethnic Nationalism and International Conflict: The Case of Serbia","readingPages":["130-166"]},
{"readingDate":"11/05/19","readingAuthors":["Derek S. Reveron","Kathleen A. Mahoney-Norris"],"readingTitle":"Human Security in a Borderless World ","readingPages":["103-120"]},
{"readingDate":"11/05/19","readingAuthors":["Ole M. Theisen", "Helge Holtermann", "Halvard Buhaug"],"readingTitle":"Climate Wars? Assessing the Claim that Drought Breeds Conflict","readingPages":["79-106"]},
{"readingDate":"11/05/19","readingAuthors":["Val Percival","Thomas Homer-Dixon"],"readingTitle":"Environmental Scarcity and Violent Conflict: The Case of South Africa","readingPages":["279-298"]},
{"readingDate":"11/08/19","readingAuthors":["Scott Sagan"],"readingTitle":"Why do States Build Nuclear Weapons? Three Models in Search of the Bomb","readingPages":["54-86"]},
{"readingDate":"11/08/19","readingAuthors":["Michael D. Cohen"],"readingTitle":"Fear and Loathing: When Nuclear Proliferation Emboldens","readingPages":["56-71"]},
{"readingDate":"11/08/19","readingAuthors":["Sumit Ganguly","S. Paul Kapur"],"readingTitle":"India, Pakistan, and the Bomb: Debating Nuclear Stability in South Asia","readingPages":["23-60"]},
{"readingDate":"11/12/19","readingAuthors":["Barry R. Posen","Andrew L. Ross"],"readingTitle":"Competing Visions for US Grand Strategy","readingPages":["5-43"]},
{"readingDate":"11/12/19","readingAuthors":["John J. Mearsheimer","Stephen M. Walt"],"readingTitle":"The Case for Offshore Balancing: A Superior US Grand Strategy","readingPages":["70-83"]},
{"readingDate":"11/12/19","readingAuthors":["Hal Brands","Peter Feaver"],"readingTitle":"Should America Retrench? The Battle Over Offshore Balancing","readingPages":["164-169"]},
{"readingDate":"11/12/19","readingAuthors":["Mira Rapp-Hooper","Rebecca Friedman Lissner"],"readingTitle":"The Open World: What America can Achieve After Trump","readingPages":["18-25"]},
{"readingDate":"11/19/19","readingAuthors":["Harlan Cleveland"],"readingTitle":"Crisis Diplomacy","readingPages":["638-649"]},
{"readingDate":"11/19/19","readingAuthors":["Anne E. Sartori"],"readingTitle":"The Might of the Pen: A Reputational Theory of Communication in International Disputes","readingPages":["121-149"]},
{"readingDate":"11/19/19","readingAuthors":["James P. O’Leary"],"readingTitle":"Economic Warfare and Strategic Economics","readingPages":["179-206"]},
{"readingDate":"11/19/19","readingAuthors":["Inwook Kim","Jung-Chul Lee"],"readingTitle":"Sanctions for Nuclear Inhibition: Comparing Sanction Conditions between Iran and North Korea","readingPages":["95-122"]},
{"readingDate":"11/22/19","readingAuthors":["Kenneth W. Abbott","Duncan Snidal"],"readingTitle":"Why States Act through Formal International Organizations","readingPages":["3-32"]},
{"readingDate":"11/22/19","readingAuthors":["Kurt Leffler"],"readingTitle":"The ADMM-Plus and the US Department of Defense: Beyond the Talk Shop Paradigm","readingPages":["123-130"]},
{"readingDate":"11/22/19","readingAuthors":["James D. Morrow"],"readingTitle":"Alliances: Why Write Them Down?","readingPages":["63-83"]},
{"readingDate":"11/22/19","readingAuthors":["Brett Ashley Leeds"],"readingTitle":"Do Alliances Deter Aggression? The Influence of Military Alliances on the Initiation of Militarized Interstate Disputes","readingPages":["427-439"]},
{"readingDate":"11/26/19","readingAuthors":["Elias Gotz"],"readingTitle":"Putin, the State, and War: The Causes of Russia’s Near Abroad Assertion Revisited","readingPages":["228-253"]},
{"readingDate":"11/26/19","readingAuthors":["Clifford Gaddy","Michael O’Hanlon"],"readingTitle":"Toward a Reaganov Russia: Russian Security Policy After Putin","readingPages":["205-221"]},
{"readingDate":"11/26/19","readingAuthors":["Emma Ashford"],"readingTitle":"Not-So-Smart Sanctions: The Failure of Western Restrictions Against Russia","readingPages":["114-125"]},
{"readingDate":"11/26/19","readingAuthors":["Thijs Van de Graaf","Jeff Colgan"],"readingTitle":"Russian Gas Games or Well-Oiled Conflict? Energy Security and the 2014 Ukraine Crisis","readingPages":["59-64"]},
{"readingDate":"12/03/19","readingAuthors":["Andrew Scobell"],"readingTitle":"The South China Sea and US-China Rivalry","readingPages":["199-224"]},
{"readingDate":"12/03/19","readingAuthors":["Van Jackson"],"readingTitle":"Red Teaming the Rebalance: The Theory and Risks of US Asia Strategy","readingPages":["365-388"]},
{"readingDate":"12/03/19","readingAuthors":["Aaron L. Friedberg"],"readingTitle":"The Debate Over US China Strategy","readingPages":["89-110"]},
{"readingDate":"12/06/19","readingAuthors":["Leon V. Sigal"],"readingTitle":"Disarming Strangers: Nuclear Diplomacy with North Korea","readingPages":["1-14","17-19","20-38","52-65","71-84","113-133","150-171" ]},
{"readingDate":"12/06/19","readingAuthors":["N. D. Anderson"],"readingTitle":"Explaining North Korea’s Nuclear Ambitions: Power and Position on the Korean Peninsula","readingPages":["621-641"]},
{"readingDate":"12/06/19","readingAuthors":["Darcie Draudt","John K. Warden"],"readingTitle":"The Strategic Rationale for Maritime Tension Reduction in the Yellow Sea","readingPages":["183-197"]},
{"readingDate":"12/13/19","readingAuthors":["Stephen Kinzer"],"readingTitle":"All the Shah’s Men","readingPages":["ix-xxiii","17-29","47-101","115-118","123","133","150-166","193-215"]},
{"readingDate":"12/13/19","readingAuthors":["Kayhan Barzegar","Abdolrasool Divsallar"],"readingTitle":"Political Rationality in Iranian Foreign Policy","readingPages":["39-53"]},
{"readingDate":"12/13/19","readingAuthors":["Eliot A. Cohen","Eric S. Edelman","Ray Takeyh"],"readingTitle":"Time to Get Tough on Tehran: Iran Policy after the Deal","readingPages":["64-75"]},
{"readingDate":"12/13/19","readingAuthors":["Vali Nasr"],"readingTitle":"Iran Among the Ruins: Tehran’s Advantage in a Turbulent Middle East","readingPages":["108-118"]},
{"readingDate":"12/17/19","readingAuthors":["Martha Crenshaw"],"readingTitle":"The Causes of Terrorism","readingPages":["379-399"]},
{"readingDate":"12/17/19","readingAuthors":["Michael J. Boyle"],"readingTitle":"The War on Terror in American Grand Strategy","readingPages":["191-209"]},
{"readingDate":"12/17/19","readingAuthors":["Anne L. Clunan"],"readingTitle":"The Fight against Terrorist Financing","readingPages":["569-596"]},
{"readingDate":"12/17/19","readingAuthors":["Seung-Whan Choi"],"readingTitle":"Economic Sanctions, Poverty, and International Terrorism: An Empirical Analysis","readingPages":["217-245"]}
];
