var IS2CourseDaysJSON = [
{"courseDayTitle":"IS2-01","courseDayDate":"01/07/20"},
{"courseDayTitle":"IS2-02","courseDayDate":"01/10/20"},
{"courseDayTitle":"IS2-03","courseDayDate":"01/14/20"},
{"courseDayTitle":"IS2-04","courseDayDate":"01/17/20"},
{"courseDayTitle":"IS2-05","courseDayDate":"01/21/20"},
{"courseDayTitle":"IS2-06","courseDayDate":"01/24/20"},
{"courseDayTitle":"IS2-07","courseDayDate":"01/28/20"},
{"courseDayTitle":"IS2-08","courseDayDate":"01/31/20"},
{"courseDayTitle":"IS2-09","courseDayDate":"02/04/20"},
{"courseDayTitle":"IS2-10","courseDayDate":"02/11/20"},
{"courseDayTitle":"IS2-11","courseDayDate":"02/14/20"},
{"courseDayTitle":"IS2-12","courseDayDate":"02/18/20"},
{"courseDayTitle":"IS2-13","courseDayDate":"02/25/20"},
{"courseDayTitle":"IS2-14","courseDayDate":"03/3/20"},
{"courseDayTitle":"IS2-15","courseDayDate":"03/4/20"}];

var IS2ReadingsJSON = [
{"readingDate":"01/07/20","readingAuthors":["Antulio J. Echevarria II"],"readingTitle":"Military Strategy: A Very Short Introduction","readingPages":["1-12"]},
{"readingDate":"01/07/20","readingAuthors":["Carl Von Clausewitz"],"readingTitle":"On War, Book VIII: Ch. 6.B War is an Instrument of Policy","readingPages":["605-610"]},
{"readingDate":"01/07/20","readingAuthors":["Barry Posen"],"readingTitle":"The Sources of Military Doctrine, Ch 1","readingPages":["13-33"]},
{"readingDate":"01/07/20","readingAuthors":["HR McMaster"],"readingTitle":"Dereliction of Duty","readingPages":["323-334", "Skim 42-61", "62-136"]},
{"readingDate":"01/10/20","readingAuthors":["Richard K. Betts"],"readingTitle":"Is Strategy an Illusion?","readingPages":["5-50"]},
{"readingDate":"01/10/20","readingAuthors":["Richard K. Betts"],"readingTitle":"Pick Your Poison: America has many options in Syria, None are Good","readingPages":["all"]},
{"readingDate":"01/14/20","readingAuthors":["Graham Allison & Philip Zelikow"],"readingTitle":"Essence of Decision Explaining the Cuban Missile Crisis","readingPages":["13-26", "40-54"]},
{"readingDate":"01/14/20","readingAuthors":["James Fearon"],"readingTitle":"Rationalist Explanations for War","readingPages":["379-414"]},
{"readingDate":"01/14/20","readingAuthors":["Navin A. Bapat"],"readingTitle":"A Game Theoretic Analysis of the Afghan Surge","readingPages":["217-222", "228-234"]},
{"readingDate":"01/17/20","readingAuthors":["Graham Allison & Philip Zelikow"],"readingTitle":"Essence of Decision Explaining the Cuban Missile Crisis","readingPages":["143-147", "153-158", "164-185"]},
{"readingDate":"01/17/20","readingAuthors":["Barry Posen"],"readingTitle":"The Sources of Military Doctrine, Ch 2","readingPages":["41-59"]},
{"readingDate":"01/17/20","readingAuthors":["Todd Greentree"],"readingTitle":"Bureaucracy Does its Thing: US Performance and the Institutional Dimension of Strategy in Afghanistan","readingPages":["325-356"]},
{"readingDate":"01/21/20","readingAuthors":["Graham Allison & Philip Zelikow"],"readingTitle":"Essence of Decision Explaining the Cuban Missile Crisis","readingPages":["255-258", "294-311"]},
{"readingDate":"01/21/20","readingAuthors":["Stephen Krasner"],"readingTitle":"Are Bureaucracies Important? Or Allison Wonderland","readingPages":["159-179"]},
{"readingDate":"01/21/20","readingAuthors":["Kevin Marsh"],"readingTitle":"Obama's Surge: A Bureaucratic Politics Analysis of the Decision to Order a Troop Surge in the Afghanistan War","readingPages":["265-288"]},
{"readingDate":"01/24/20","readingAuthors":["Robert Jervis"],"readingTitle":"Hypothesis on Misperception","readingPages":["189-199"]},
{"readingDate":"01/24/20","readingAuthors":["Yuen Khong"],"readingTitle":"Analogies at War","readingPages":["Skim 3-18", "71-96"]},
{"readingDate":"01/24/20","readingAuthors":["Aaron Rapport"],"readingTitle":"The Long and Short of It: Cognitive Constraints on Leaders' Assessments of 'Post-War' Iraq","readingPages":["133-171"]},
{"readingDate":"01/28/20","readingAuthors":["Michael Walzer"],"readingTitle":"Just and Unjust Wars","readingPages":["13-16", "21-25", "34-47", "127-159"]},
{"readingDate":"01/28/20","readingAuthors":["David P. Fidler"],"readingTitle":"Just and Unjust War, Use of Forc & Coercion: An Ethical Inquiry with Cyber Illustrations","readingPages":["37-49"]},
{"readingDate":"01/28/20","readingAuthors":["David J. Lonsdale"],"readingTitle":"Warfighting for Cyber Deterrence: a Strategic and Moral Imperative","readingPages":["409-429"]},
{"readingDate":"01/28/20","readingAuthors":["Nina Kollars & Jacquelyn Schneider"],"readingTitle":"Defending Forward: The 2018 Cyber Strategy is Here","readingPages":["all"]},
{"readingDate":"01/31/20","readingAuthors":["William E. Rapp"],"readingTitle":"Civil-Military Relations: The Role of Military Leaders in Strategy Making","readingPages":["13-26"]},
{"readingDate":"01/31/20","readingAuthors":["Peter D. Feaver"],"readingTitle":"The Right to be Right: Civil Military Relations and the Iraq Surge Decision","readingPages":["87-125"]},
{"readingDate":"02/04/20","readingAuthors":["Antullio J. Echevarria II"],"readingTitle":"Toward and American Way of War","readingPages":["1-18"]},
{"readingDate":"02/04/20","readingAuthors":["Christopher M. Dougherty"],"readingTitle":"Why America Needs a New Way of War","readingPages":["1-38"]},
{"readingDate":"02/04/20","readingAuthors":["James M. Mattis"],"readingTitle":"Summary of the 2018 National Defense Strategy of the United States","readingPages":["all"]},
{"readingDate":"02/11/20","readingAuthors":["DoD"],"readingTitle":"SOUTHCOM & AFRICOM Posture Statements","readingPages":["Skim, Focus on Supporting Partner States"]},
{"readingDate":"02/11/20","readingAuthors":["Stephen Biddle, Julia Macdonald, & Ryan Baker"],"readingTitle":"Small Footprint Small Payoff The Military Effectiveness of Security Force Assistance","readingPages":["1-18", "38-45"]},
{"readingDate":"02/11/20","readingAuthors":["Kersti Larsdotter"],"readingTitle":"Security Assistance in Africa The Case for Less","readingPages":["25-34"]},
{"readingDate":"02/11/20","readingAuthors":["R. Evan Ellis"],"readingTitle":"The US Military in Support of Strategic Objectives in Latin America and the Carribbean","readingPages":["27-38"]},
{"readingDate":"02/14/20","readingAuthors":["N/A"],"readingTitle":"Research & Writing Day","readingPages":["none"]},
{"readingDate":"02/18/20","readingAuthors":["DoD"],"readingTitle":"CENTCOM Posture Statement","readingPages":["Skim, Focus on VEOs"]},
{"readingDate":"02/18/20","readingAuthors":["Stephanie Carvin"],"readingTitle":"The Trouble with Targeted Killing","readingPages":["529-555"]},
{"readingDate":"02/18/20","readingAuthors":["Daniel Byman"],"readingTitle":"Why Drones Work: The Case for Washington's Weapon of Choice","readingPages":["32-43"]},
{"readingDate":"02/18/20","readingAuthors":["Audrey Kurth Cronin"],"readingTitle":"Why Drones Fail: When Tactics Drive Strategy","readingPages":["44-54"]},
{"readingDate":"02/18/20","readingAuthors":["Javier Jordan"],"readingTitle":"The Effectiveness of the Drone Campaign Against Al Queda Central: A Case Study","readingPages":["4-29"]},
{"readingDate":"02/25/20","readingAuthors":["DoD"],"readingTitle":"EUCOM Posture Statement","readingPages":["Skim Focus on shift from engagment and assurance to deterrence and defense"]},
{"readingDate":"02/25/20","readingAuthors":["Thomas C. Schelling"],"readingTitle":"The Strategy of Conflict","readingPages":["3-6", "21-28", "35-46", "207-208"]},
{"readingDate":"02/25/20","readingAuthors":["Michael Gerson"],"readingTitle":"Conventional Deterrence in the Second Nuclear Age","readingPages":["32-48"]},
{"readingDate":"02/25/20","readingAuthors":["Martin Zapfe"],"readingTitle":"Deterrence from the Ground Up: Understanding NATO's Enhanced Foreign Presence","readingPages":["147-160"]},
{"readingDate":"02/25/20","readingAuthors":["Alexander Lanoszka and Michael A. Hunzeker"],"readingTitle":"Confronting the Anti-Acess/Area-Denial and Precision Strike Challenge in the Baltic Region","readingPages":["12-18"]},
{"readingDate":"03/03/20","readingAuthors":["DoD"],"readingTitle":"IDOPACOM Posture Statement","readingPages":["Skim Focus on Offshore Control or Strategies for Augmenting US Forward Presence"]},
{"readingDate":"03/03/20","readingAuthors":["TX Hammes"],"readingTitle":"Offshore Control: A Proposed Strategy for an Unlikely Conflict","readingPages":["1-16"]},
{"readingDate":"03/03/20","readingAuthors":["Robert Haddick"],"readingTitle":"Fire on the Water: China, America, and the Future of the Pacific","readingPages":["77-159", "Skim 203-218"]},
{"readingDate":"03/04/20","readingAuthors":["DoD"],"readingTitle":"NORTHCOM Posture Statement","readingPages":["Skim, Focus on Ballistic Missle Defense"]},
{"readingDate":"03/04/20","readingAuthors":["John Gibilterra"],"readingTitle":"Conditional Deterrence and Missile Defense","readingPages":["64-73"]},
{"readingDate":"03/04/20","readingAuthors":["JD Crouch, Robert Joseph, Keith B. Payne, Jayson Roehl"],"readingTitle":"Missile Defense and National Security The Need to Sustain a Balanced Approach","readingPages":["1-9"]},
{"readingDate":"03/04/20","readingAuthors":["Joseph T. Buontempo"],"readingTitle":"A Trajectory for Homeland Ballistic Missile Defense","readingPages":["99-109"]}];
