var JWCourseDaysJSON = [
{"courseDayTitle":"JW-01","courseDayDate":"03/16/20"},
{"courseDayTitle":"JW-02","courseDayDate":"03/17/20"},
{"courseDayTitle":"JW-03","courseDayDate":"03/19/20"},
{"courseDayTitle":"JW-04","courseDayDate":"03/20/20"},
{"courseDayTitle":"JW-05","courseDayDate":"03/23/20"},
{"courseDayTitle":"JW-06","courseDayDate":"03/24/20"},
{"courseDayTitle":"JW-07","courseDayDate":"03/26/20"},
{"courseDayTitle":"JW-08","courseDayDate":"03/27/20"},
{"courseDayTitle":"JW-09","courseDayDate":"03/30/20"},
{"courseDayTitle":"JW-10","courseDayDate":"03/31/20"},
{"courseDayTitle":"JW-11","courseDayDate":"04/06/20"},
{"courseDayTitle":"JW-12","courseDayDate":"04/07/20"},
{"courseDayTitle":"JW-13","courseDayDate":"04/09/20"},
{"courseDayTitle":"JW-14","courseDayDate":"04/10/20"},
{"courseDayTitle":"JW-15","courseDayDate":"04/13/20"},
{"courseDayTitle":"JW-16","courseDayDate":"04/14/20"},
{"courseDayTitle":"JW-17","courseDayDate":"04/16/20"},
{"courseDayTitle":"JW-18","courseDayDate":"04/17/20"},
{"courseDayTitle":"JW-19","courseDayDate":"04/20/20"},
{"courseDayTitle":"JW-20","courseDayDate":"04/21/20"},
{"courseDayTitle":"JW-21","courseDayDate":"04/23/20"},
{"courseDayTitle":"JW-22","courseDayDate":"04/27/20"},
{"courseDayTitle":"JW-23","courseDayDate":"04/28/20"},
{"courseDayTitle":"JW-24","courseDayDate":"05/30/20"},
{"courseDayTitle":"JW-25","courseDayDate":"05/04/20"},
{"courseDayTitle":"JW-26","courseDayDate":"05/05/20"},
{"courseDayTitle":"JW-27","courseDayDate":"05/07/20"},
{"courseDayTitle":"JW-28","courseDayDate":"05/08/20"},
{"courseDayTitle":"JW-29","courseDayDate":"05/11/20"}
];

var JWReadingsJSON = [
{"readingDate":"03/16/20","readingAuthors":["Rick Atkinson"],"readingTitle":"An Army at Dawn: The War in North Africa, 1942-1943","readingPages":["1-160"]},
{"readingDate":"03/16/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 5-0: Joint Planning","readingPages":["xi-xxx"]},
{"readingDate":"03/16/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 1: Doctrine for the Armed Forces","readingPages":["III-1 to III-12", "I-17 to I-19"]},
{"readingDate":"03/16/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-0: Joint Operations","readingPages":["V-4 to V-17"]},
{"readingDate":"03/16/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-08: Interorganization Cooperation","readingPages":["Skim I-1 to I-17","II-2 to II-12"]},
{"readingDate":"03/17/20","readingAuthors":["Jeffrey M. Reilly"],"readingTitle":"Operational Design: Distilling Clarity from Complexity for Decisive Action","readingPages":["1-14, 21-29"]},
{"readingDate":"03/17/20","readingAuthors":["US Army"],"readingTitle":"TRADOC Phamplet 525-5-500, Commander's Appreciation and Campaign Design","readingPages":["4-18"]},
{"readingDate":"03/17/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 5-0: Joint Planning","readingPages":["IV-1 to IV-42"]},
{"readingDate":"03/17/20","readingAuthors":["Bob Woodward"],"readingTitle":"Plan of Attack","readingPages":["52-66"]},
{"readingDate":"03/19/20","readingAuthors":["Bob Woodward"],"readingTitle":"Plan of Attack","readingPages":["1-23, 31-38, 85-95, 130-133, 177-179"]},
{"readingDate":"03/19/20","readingAuthors":["DoD"],"readingTitle":"National Military Strategy","readingPages":["1-6"]},
{"readingDate":"03/19/20","readingAuthors":["DoD"],"readingTitle":"CJCSI 3100.01D","readingPages":["1-2","Enclosures A B C G H I"]},
{"readingDate":"03/19/20","readingAuthors":["DoD"],"readingTitle":"Joint Doctrine Note 1-19","readingPages":["v-vii", "1-11"]},
{"readingDate":"03/19/20","readingAuthors":["Gen Dunford"],"readingTitle":"The Character of War and Strategic Landscape Have Changed","readingPages":["2-3"]},
{"readingDate":"03/19/20","readingAuthors":["Ronald O'Rourk"],"readingTitle":"Renewed Great Power Competition: Implications for Defense  Issues for Congress","readingPages":["1-8"]},
{"readingDate":"03/20/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 5-0: Joint Planning","readingPages":["IV-10 to IV-15 (Stop at Identify Assumptions)"]},
{"readingDate":"03/20/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 2-0: Joint Intelligence","readingPages":["ix-xvi"]},
{"readingDate":"03/20/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 2-01.2: Joint Intelligence Preparation of the Operational Environment","readingPages":["xi-xviii, Skim App B,D,E"]},
{"readingDate":"03/20/20","readingAuthors":["Joint Staff J7"],"readingTitle":"Planner's Handbook for Operational Design","readingPages":["V-1 to V-16"]},
{"readingDate":"03/20/20","readingAuthors":["Dale F. Spurlin"],"readingTitle":"The Problem Statement: What's the Problem?","readingPages":["All"]},
{"readingDate":"03/20/20","readingAuthors":["Milan Vego"],"readingTitle":"Joint Operational Warfare: Theory and Practice","readingPages":["VII-13 to VII-27, VII-29 to VII-35"]},
{"readingDate":"03/20/20","readingAuthors":["Christopher M. Schnaubelt"],"readingTitle":"Vulnerability Assessment Method Procket Guide","readingPages":["Skim 1-6, Read 7-32"]},
{"readingDate":"03/23/20","readingAuthors":["Dale C. Eikmeier"],"readingTitle":"Design for Napoleon's Corporal","readingPages":["1-11"]},
{"readingDate":"03/23/20","readingAuthors":["Jeffrey M. Reilly"],"readingTitle":"Operational Design: Distilling Clarity from Complexity for Decisive Action","readingPages":["31-58, Review Ch. 2"]},
{"readingDate":"03/23/20","readingAuthors":["Joint Staff J7"],"readingTitle":"Planner's Handbook for Operational Design","readingPages":["VI-1 to VI-7"]},
{"readingDate":"03/23/20","readingAuthors":["US JFC"],"readingTitle":"Design in Military Operations: A Primer for Joint Warfighters","readingPages":["A-1 to A-32"]},
{"readingDate":"03/24/20","readingAuthors":["None"],"readingTitle":"None","readingPages":["None"]},
{"readingDate":"03/26/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-08: Interorganization Cooperation","readingPages":["II-12 to II-18, II-21 to II-32"]},
{"readingDate":"03/26/20","readingAuthors":["ACSC"],"readingTitle":"Nigeria Planning Stuff on Canvas","readingPages":["Unknown"]},
{"readingDate":"03/26/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Study Guide on Canvas","readingPages":["Unknown"]},
{"readingDate":"03/27/20","readingAuthors":["ACSC"],"readingTitle":"Nigeria Planning Stuff on Canvas","readingPages":["Unknown"]},
{"readingDate":"03/27/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Study Guide on Canvas","readingPages":["Unknown"]},
{"readingDate":"03/30/20","readingAuthors":["Joint Staff J7"],"readingTitle":"Insights and Best Practices Focus Paper: Design and Planning","readingPages":["2-17"]},
{"readingDate":"03/30/20","readingAuthors":["David G. Perkins"],"readingTitle":"Multidomain Battle: Converging Concepts Toward a Joint Solution","readingPages":["54-57"]},
{"readingDate":"03/30/20","readingAuthors":["US Army"],"readingTitle":"The US Army in Multi Domain Operations 2028, TRADOC Phamplet 525-3-1","readingPages":["6-8"]},
{"readingDate":"03/30/20","readingAuthors":["David R. DiOrio"],"readingTitle":"Operation Unified Response - Haiti Earthqauke 2010","readingPages":["1-18"]},
{"readingDate":"03/30/20","readingAuthors":["DoD"],"readingTitle":"CDRUSSOUTHCOM, USSOUTHCOM OPORD 1-10: Support to Haiti Earthquake Relief Efforts","readingPages":["Read 3-18 (up to Tasks to Units), Skim 18-60"]},
{"readingDate":"03/30/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 5-0: Joint Planning","readingPages":["V-4 to V-20"]},
{"readingDate":"03/30/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 1: Doctrine for the Armed Forces","readingPages":["IV-1 to IV-11, IV-15 to IV-18, V-1 to V-13"]},
{"readingDate":"03/30/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-08: Interorganization Cooperation","readingPages":["IV-19 to IV-30"]},
{"readingDate":"03/31/20","readingAuthors":["Kenneth Allard"],"readingTitle":"Samoalia Lessons Learned","readingPages":["xv-xviii, 1-34, 50-59, 67-69, 78-86"]},
{"readingDate":"03/31/20","readingAuthors":["Major Michael F. Beech"],"readingTitle":"Mission Creep: A Case Study in US Involvement in Somalia, A Monograph","readingPages":["Skim 1-45"]},
{"readingDate":"03/31/20","readingAuthors":["DoD"],"readingTitle":"Jont Publication 2-01.3: Joint Intelligence Preparation of the Operational Environment","readingPages":["B-1 to B-32"]},
{"readingDate":"04/06/20","readingAuthors":["None"],"readingTitle":"None","readingPages":["None"]},
{"readingDate":"04/07/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 5-0: Joint Planning","readingPages":["VI-24 to VI-41 (Operation Assessment)"]},
{"readingDate":"04/07/20","readingAuthors":["US Army"],"readingTitle":"Operational Contract Support: Plan for Management for Leaders","readingPages":["2 pg smart card"]},
{"readingDate":"04/07/20","readingAuthors":["ACSC"],"readingTitle":"Nigeria Planning Stuff on Canvas","readingPages":["Unknown"]},
{"readingDate":"04/07/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Study Guide on Canvas","readingPages":["Unknown"]},
{"readingDate":"04/09/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 5-0: Joint Planning","readingPages":["VI-24 to VI-41 (Operation Assessment)"]},
{"readingDate":"04/09/20","readingAuthors":["US Army"],"readingTitle":"Operational Contract Support: Plan for Management for Leaders","readingPages":["2 pg smart card"]},
{"readingDate":"04/09/20","readingAuthors":["ACSC"],"readingTitle":"Nigeria Planning Stuff on Canvas","readingPages":["Unknown"]},
{"readingDate":"04/09/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Study Guide on Canvas","readingPages":["Unknown"]},
{"readingDate":"04/10/20","readingAuthors":["Linda Robinson"],"readingTitle":"US Special Operations Forces in the Philippines","readingPages":["iii-iv, 17-44"]},
{"readingDate":"04/10/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 5-0: Joint Planning","readingPages":["V-20 to V-31 (COA Development)", "VIII-4 paragraph 4abcd and App F(FDOs/FROs)", "Review IV-31 to IV-33 (Defeat & Stability Mechanisms)"]},
{"readingDate":"04/10/20","readingAuthors":["Bob Woodward"],"readingTitle":"Plan of Attack","readingPages":["75-84, 96-103, 105-106"]},
{"readingDate":"04/10/20","readingAuthors":["Joint Chiefs"],"readingTitle":"Joint Concept for Operating in Information Environment (JCOIE)","readingPages":["vii-xi, 1-6, 11-30"]},
{"readingDate":"04/13/20","readingAuthors":["LTC Joseph Blair"],"readingTitle":"The Ingrediants of Military Genius","readingPages":["1-16"]},
{"readingDate":"04/13/20","readingAuthors":["Milan Vego"],"readingTitle":"On Military Creativity","readingPages":["83-90"]},
{"readingDate":"04/14/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-13: Information Operations","readingPages":["I-1 to I-5, II-5 to II-13, IV-1 to IV-12"]},
{"readingDate":"04/14/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-12: Cyberspace Operations","readingPages":["vii-xvii"]},
{"readingDate":"04/14/20","readingAuthors":["Dina Temple Raston"],"readingTitle":"How the US Hacked ISIS","readingPages":["All"]},
{"readingDate":"04/14/20","readingAuthors":["Jennifer Leigh Phillips"],"readingTitle":"Tactical Maneuver in the Cyber Domain: Dominating the Enemy","readingPages":["14-20"]},
{"readingDate":"04/14/20","readingAuthors":["DoD"],"readingTitle":"Joint Doctrine 3-16: Joint Electromagnetic Spectrum Operations","readingPages":["v-ix, I-1 to I-11"]},
{"readingDate":"04/14/20","readingAuthors":["CRS"],"readingTitle":"Defense Primer: Electronic Warfare","readingPages":["All"]},
{"readingDate":"04/14/20","readingAuthors":["CRS"],"readingTitle":"Defense Primer: Military Use of Electromagnetic Spectrum","readingPages":["All"]},
{"readingDate":"04/14/20","readingAuthors":["CRS"],"readingTitle":"Defense Primer: Information Operations","readingPages":["All"]},
{"readingDate":"04/14/20","readingAuthors":["CRS"],"readingTitle":"Defense Primer: Convergence of Cyberspace Operations and Electronic Warfare","readingPages":["All"]},
{"readingDate":"04/16/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-05: Special Operations","readingPages":["ix-xv, I-1 to I-10, II-1 to II-18"]},
{"readingDate":"04/16/20","readingAuthors":["JW Dept"],"readingTitle":"Joint Warfighting Capabilities Primer: Joint Special Operations","readingPages":["114-127"]},
{"readingDate":"04/16/20","readingAuthors":["US Army HQ"],"readingTitle":"Army Docrine Pub 3-0: Unified Land Operations","readingPages":["3-1 to 3-13"]},
{"readingDate":"04/16/20","readingAuthors":["US Marine HQ"],"readingTitle":"MCDP 1-0","readingPages":["I-1 to I-5 (Stop at instruments of national power), I-13 (Roles and Functions) to I-17, 2-6 to 2-20"]},
{"readingDate":"04/16/20","readingAuthors":["JW Dept"],"readingTitle":"Joint Warfighting Capabilities Primer: US Army and Marine Corps","readingPages":["57-74, 93-107"]},
{"readingDate":"04/16/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-31: Command and Control for Joint Land Operations","readingPages":["ix-xviii"]},
{"readingDate":"04/17/20","readingAuthors":["US Navy"],"readingTitle":"Navy Warfare Pub 3-32: Maritime Operations at the Operational Level of War","readingPages":["I-1 to I-7"]},
{"readingDate":"04/17/20","readingAuthors":["US Navy"],"readingTitle":"Composite Warfare: Maritime Operations at the tactical level of war","readingPages":["1-1 to 1-5, 3-1 to 3-8, Skim 4-1 to 5-6, Read 7-1 to 7-8, 8-1 to 8-5"]},
{"readingDate":"04/17/20","readingAuthors":["JW Dept"],"readingTitle":"Joint Warfighting Capabilities Primer: US Navy","readingPages":["75-92"]},
{"readingDate":"04/17/20","readingAuthors":["Naval Media Center"],"readingTitle":"All Hands: Magazine of the US Navy","readingPages":["Skim 3-19 and 32-33"]},
{"readingDate":"04/17/20","readingAuthors":["Milan Vego"],"readingTitle":"On Naval Warfare","readingPages":["73-92"]},
{"readingDate":"04/20/20","readingAuthors":["DIA"],"readingTitle":"Challenges to Security in Space","readingPages":["7-37"]},
{"readingDate":"04/20/20","readingAuthors":["USAF"],"readingTitle":"AF Doctrine Annex 3-14: Counterspace Operations","readingPages":["2-33"]},
{"readingDate":"04/20/20","readingAuthors":["US Army"],"readingTitle":"Field Manual 3-14: Army Space Operations","readingPages":["1-1 to 1-13"]},
{"readingDate":"04/20/20","readingAuthors":["USMC"],"readingTitle":"Marine Corps Concept for Space Operations","readingPages":["1-11"]},
{"readingDate":"04/20/20","readingAuthors":["Donald Trump"],"readingTitle":"Space Policy Directive 4: Establishment of the US Space Force","readingPages":["All"]},
{"readingDate":"04/21/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-30: Command and Control of for Joint Air Operations","readingPages":["I-1 to II-28", "App F G"]},
{"readingDate":"04/21/20","readingAuthors":["JW Dept"],"readingTitle":"Joint Warfighting Capabilities Primer: USAF","readingPages":["6-25"]},
{"readingDate":"04/21/20","readingAuthors":["Ben Lambeth"],"readingTitle":"Air Power Against Terror: America's Conduct of Operation Enduring Freedom","readingPages":["62-103"]},
{"readingDate":"04/23/20","readingAuthors":["National Guard Bureau"],"readingTitle":"2018 National Guard Bureau Posture Statement","readingPages":["Skim 1-26"]},
{"readingDate":"04/23/20","readingAuthors":["David W. Giles"],"readingTitle":"Defending the Homeland: The Massachusttes National Guard Responds to the 2013 Boston Marathon Bombings","readingPages":["1-21"]},
{"readingDate":"04/23/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-27: Homeland Defense","readingPages":["vii-xv and A-1 to A-7"]},
{"readingDate":"04/23/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 3-28: Defense Support of Civil Authorities","readingPages":["ix-xix"]},
{"readingDate":"04/23/20","readingAuthors":["Ryan Burke"],"readingTitle":"Toward a Unified Military Response: Hurricane Sandy and the Dual Status Commander","readingPages":["7-21"]},
{"readingDate":"04/23/20","readingAuthors":["DHS"],"readingTitle":"National Response Framework, 3rd Ed.","readingPages":["i-ii, 1-19"]},
{"readingDate":"04/23/20","readingAuthors":["JW Dept"],"readingTitle":"Joint Warfighting Capabilities Primer: Nagtional Guard","readingPages":["143-148"]},
{"readingDate":"04/27/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 4-0: Joint Logistics","readingPages":["ix-xviii, I-1 to I-10"]},
{"readingDate":"04/27/20","readingAuthors":["Unk"],"readingTitle":"Operational Contracting Support","readingPages":["Video"]},
{"readingDate":"04/27/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 4-10: Operational Contract Support","readingPages":["ix-xvii", "I-1 to I-4 (stop at 4.Key Terminology)", "I-8 to I-16 (stop at 8.Prevention of Fraud)"]},
{"readingDate":"04/27/20","readingAuthors":["Alice Trvion"],"readingTitle":"Leveraging our Warfighting Capabilities through the Lens of Operational Contract Support","readingPages":["4-14"]},
{"readingDate":"04/27/20","readingAuthors":["Charles R. Shrader"],"readingTitle":"A War of Logistics: Parachutes and Porters in Indochina","readingPages":["xv-xvi, 1-9"]},
{"readingDate":"04/27/20","readingAuthors":["Kenneth Allard"],"readingTitle":"Somalia Lessons Learned","readingPages":["Read 40-46", "74-75", "(Review xv-xviii, 1-34, 50-59, 67-69, 78-86 from JW-514)"]},
{"readingDate":"04/27/20","readingAuthors":["Robert C. Owen"],"readingTitle":"Air Mobility: A Brief History of the American Express","readingPages":["240-253"]},
{"readingDate":"04/27/20","readingAuthors":["JW Dept"],"readingTitle":"Joint Warfighting Capabilities Primer: Transportation Command","readingPages":["136-142"]},
{"readingDate":"04/27/20","readingAuthors":["ACSC"],"readingTitle":"Quizlet Module (Some sort of CBT everyone should do I think)","readingPages":["UNK"]},
{"readingDate":"04/28/20","readingAuthors":["None"],"readingTitle":"None","readingPages":["None"]},
{"readingDate":"04/30/20","readingAuthors":["ACSC"],"readingTitle":"Nigeria Planning Stuff on Canvas","readingPages":["UNK"]},
{"readingDate":"04/30/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Study Guide on Canvas","readingPages":["UNK"]},
{"readingDate":"05/04/20","readingAuthors":["ACSC"],"readingTitle":"Nigeria Planning Stuff on Canvas","readingPages":["UNK"]},
{"readingDate":"05/04/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Study Guide on Canvas","readingPages":["UNK"]},
{"readingDate":"05/05/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 5-0: Joint Planning","readingPages":["V-31 to V-42"]},
{"readingDate":"05/05/20","readingAuthors":["Jeffrey M. Reilly"],"readingTitle":"Operational Design: Distilling Clarity from Complexity for Decisive Action","readingPages":["65-81"]},
{"readingDate":"05/05/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Guidance, research materials, etc. on Canvas","readingPages":["Unk"]},
{"readingDate":"05/05/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Study Guide on Canvas","readingPages":["UNK"]},
{"readingDate":"05/07/20","readingAuthors":["DoD"],"readingTitle":"Joint Publication 5-0: Joint Planning","readingPages":["V-42 to V-45, App G & Review VI-24 to VI-41"]},
{"readingDate":"05/07/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Guidance, research materials, etc. on Canvas","readingPages":["Unk"]},
{"readingDate":"05/07/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Study Guide on Canvas","readingPages":["UNK"]},
{"readingDate":"05/08/20","readingAuthors":["None"],"readingTitle":"None","readingPages":["None"]},
{"readingDate":"05/11/20","readingAuthors":["ACSC"],"readingTitle":"JPEX Scenario Planning Guidance, Research Materials on Canvas","readingPages":["UNK"]},
{"readingDate":"05/11/20","readingAuthors":["ACSC"],"readingTitle":"JW Planning Guide Study Guide","readingPages":["UNK"]},
{"readingDate":"05/11/20","readingAuthors":["ACSC"],"readingTitle":" ","readingPages":["UNK"]},
];
